//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballML.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Juegos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Juegos()
        {
            this.Jugadas = new HashSet<Jugadas>();
        }
    
        public int IDJuego { get; set; }
        public int Equipo1ID { get; set; }
        public int Equipo2ID { get; set; }
        public int Ganador { get; set; }
        public Nullable<int> OfensivasTeam1 { get; set; }
        public Nullable<int> OfensivasTeam2 { get; set; }
        public Nullable<int> DefensivasTeam1 { get; set; }
        public Nullable<int> DefensivasTeam2 { get; set; }
        public Nullable<int> FaltasTeam1 { get; set; }
        public Nullable<int> FaltasTeam2 { get; set; }
        public Nullable<int> GolesTeam1 { get; set; }
        public Nullable<int> GolesTeam2 { get; set; }
    
        public virtual Equipos Equipos { get; set; }
        public virtual Equipos Equipos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jugadas> Jugadas { get; set; }
    }
}
