//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballML.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jugadas
    {
        public int IDJuego { get; set; }
        public int NumJugada { get; set; }
        public Nullable<int> Equipo { get; set; }
        public string TipoJugada { get; set; }
        public string CategoriaJugada { get; set; }
        public Nullable<int> Minuto { get; set; }
        public Nullable<int> Segundo { get; set; }
    
        public virtual Equipos Equipos { get; set; }
        public virtual Juegos Juegos { get; set; }
    }
}
