//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballML.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimulResults
    {
        public Nullable<int> OfensivasTeam1 { get; set; }
        public Nullable<int> OfensivasTeam2 { get; set; }
        public Nullable<int> DefensivasTeam1 { get; set; }
        public Nullable<int> DefensivasTeam2 { get; set; }
        public Nullable<int> FaltasTeam1 { get; set; }
        public Nullable<int> FaltasTeam2 { get; set; }
        public Nullable<int> Ganador { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public int id { get; set; }
    }
}
